### ISSUE TITLE
Feature Request: Custom Body

### ISSUE THREAD

**Issue by miskolc** [ShopRunner/jupyter-notify#13]
It would be really nice if I could set a custom message for each cell I'm running. The use case for this is when I'm running multiple cells and I would like to be able to distinguish between those them. Having the same message for all cells doesn't enable me to do that.

In terms of the actual API, I was thinking that the message should appear after `%%notify` like this:

    %%notify First Cell Message
    %%notify Second Cell Message

**Comment by mdagost** [comment]
Thanks for the request!  That's a good idea.  We should probably be able to get to this in the next week or two.

**Comment by htorrence** [comment]
Custom messages are now available! 

Syntax is ```%%notify -m "First Cell Message"```.

**Comment by negati-ve** [comment]
why doesn't `%%notify -m "First Cell Message"+str_var` work?

**Comment by mdagost** [comment]
@negati-ve Looks like this has to do with how the magics do variable expansion in their arguments.  They use a `$` like bash (see [this](https://stackoverflow.com/questions/14409167/how-to-pass-a-variable-to-magic-%C2%B4run%C2%B4-function-in-ipython) StackOverflow question).  Also, you have to explicitly construct a string with quotes inside the quotes.  So the following works for me:

```
secs = "5"
message = "'Waited {} seconds...'".format(secs)
```

```
%%notify -m $message
import time
time.sleep(5)
```
