### ISSUE TITLE
only for IPython kernel?

### ISSUE THREAD

**Issue by goretkin** [ShopRunner/jupyter-notify#17]
This looks like exactly what I need. Could you clarify whether this is only for the IPython kernel, or if there's a way to have this magic work in other kernels?

**Comment by mdagost** [comment]
I hadn't tried in IRKernel or any others.  Which are you interested in?  A cursory look turns up these links, which suggest that the cell magics are python only:

https://github.com/IRkernel/IRkernel/issues/244
https://github.com/jupyter/notebook/issues/746

Sorry!

**Comment by goretkin** [comment]
I was interested in using it in IJulia. I thought there might have been jupyter-level magics, but thank you for the references that indicate otherwise!

**Comment by mdagost** [comment]
Yeah, from the IJulia kernel README:

>One difference from IPython is that the IJulia kernel does not use "magics", which are special commands prefixed with % or %% to execute code in a different language. Instead, other syntaxes to accomplish the same goals are more natural in Julia, work in environments outside of IJulia code cells, and are often more powerful.

Sorry!

**Comment by jcb91** [comment]
@goretkin For non-python kernels, you might consider using the frontend nbextension [notify](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/b9ee02d86f94015ce7eadc78266804c632d60726/src/jupyter_contrib_nbextensions/nbextensions/notify), available as part of [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions). That nbextension works for any kernel, but decides whether to notify for _each_ cell, based on the execution time of each cell, so it's not a direct analog of the functionality provided here.
