### ISSUE TITLE
Change proposals

### ISSUE THREAD

**Issue by Darel13712** [ShopRunner/jupyter-notify#20]
Hello, I don't know how to make a pull request so I will explain my proposals here.
- I would like notification message to focus browser on tab which created it on click and then close itself.
I assume this should be done if we add 
```javascript
notification.onclick = function () 
{
    window.focus();
    this.close();
};
```
right after `var notification` creation in notify.js. We can also focus on the very cell that finished, but I'm not sure how to do it.
- "Jupyter Notebook" is not very informative title if you work with multiple notebooks at once. Let's change it to `document.title` so you know which one caused notification.
- "Cell Execution Has Finished!!" is not a song name. I think "Cell execution has finished!" is prettier for a default message.
- You use favicon.ico as an icon which is of very poor quality why not use current jupyter logo like [this one](https://avatars3.githubusercontent.com/u/7388996?v=4&s=400 )?

Let me know what you think about this.

**Comment by Darel13712** [comment]
@mdagost I think it is possible to create a bot that sends you a message via telegram when a cell has finished, do you think it's worth implementing?

**Comment by mdagost** [comment]
I'm not familiar with Telegram.  I'm guessing it's like Slack?  That seems like a decent amount of work but could be a cool feature...

**Comment by Darel13712** [comment]
More like whatsapp. And not very difficult as fas as I know, there is a python package to send messages to it. I'll take a look on the weekend.

**Comment by Darel13712** [comment]
@mdagost  I think you can close this issue.
