### ISSUE TITLE
Is it possible to keep the notification popup for longer?

### ISSUE THREAD

**Issue by obaslan** [ShopRunner/jupyter-notify#22]
The notification popup goes away after a while. Is it possible to keep it open until the user closes? Is this something that the operating system decides?

**Comment by mdagost** [comment]
Hey @obaslan !  Yep--see the options section of the `README`:

```
require_interaction - Boolean, default False. When this is true, notifications will remain on screen until dismissed. This feature is currently only available in Google Chrome.
```
