### ISSUE TITLE
No action on-click

### ISSUE THREAD

**Issue by obaslan** [ShopRunner/jupyter-notify#27]
When I click on the body of the notification, no action is performed. It is supposed to go to the very tab according to the documentation.

Also, would it be possible to add other actions such as dismissing the notification when clicked?

I use chrome in windows 8.1.

**Comment by mdagost** [comment]
Which version of the extension are you using, and how did you install it?  I just tested the latest version from PyPI and it does move you to the tab.  I'm on Chrome on a Mac.

Also, on the Mac you do get an option to close the notification on the right (or it just goes away if stickiness is not enabled...)

**Comment by obaslan** [comment]
It works now after reinstalling.

I can close the notification by clicking on the top right corner. I thought it would be better to customize the on-click behavior to include the dismissing.
