### ISSUE TITLE
plans to add to nbextensions

### ISSUE THREAD

**Issue by nick-youngblut** [ShopRunner/jupyter-notify#28]
Just curious: any plans to add `jupyter-notify` to `nbextensions`?

**Comment by mdagost** [comment]
Interesting!  I didn't know about `nbextensions`.  I'll take a look and see what that would involve.  Thanks!

**Comment by mdagost** [comment]
After looking, it's not clear to me that pure python magics like this one are supported by `nbextensions`.  Those look to be javascript extensions.  I've filed an issue on that repo to ask though...
