### ISSUE TITLE
Problem with installation (basic)

### ISSUE THREAD

**Issue by FavioVazquez** [ShopRunner/jupyter-notify#3]
This is very basic, but for some reason I can't use 

``git clone git@github.com:ShopRunner/jupyter-notify.git``

Output:

```
Permission denied (publickey).
fatal: Could not read from remote repository.
```

So why not just put in the documentation just:

``git clone https://github.com/ShopRunner/jupyter-notify.git``

**Comment by mdagost** [comment]
Oh interesting.  I'll have to figure out why that's the case.  Also, I'm in the process of pushing it to PyPI so it can just be pip installed as well.

**Comment by FavioVazquez** [comment]
Great! @mdagost. Do you need any help with that? I've published to PyPI.

**Comment by mdagost** [comment]
It's up on PyPI now and is pip installable.
