### ISSUE TITLE
Make this work on Google Colaboratory

### ISSUE THREAD

**Issue by msramalho** [ShopRunner/jupyter-notify#32]
**Google** now has online colaborative jupyter-like notebooks, and it would be awesome for this magic to work there as well. 

[Google Colaboratory](https://colab.research.google.com/)

**Comment by mdagost** [comment]
That would be cool.  But from what I can tell, Colaboratory isn't standard Jupyter and doesn't seem to support extensions.  Is there anything that makes you think Colaboratory is extendable?
