### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by NP-compete** [ShopRunner/jupyter-notify#40]
Javascript Error: $ is not defined

**Comment by diogo-cruz** [comment]
It might be related to this issue: [https://github.com/jupyterlab/jupyterlab/issues/5608#issuecomment-438080874](url)

**Comment by StefanBrand** [comment]
For reference (copied from https://github.com/jupyterlab/jupyterlab/issues/5608#issuecomment-438080874):

> The jquery $ is not defined in JupyterLab. If you need to load some arbitrary javascript onto the page, you might be able to do it with something like https://stackoverflow.com/a/14521482. Just be aware that sometimes loading javascript on the page can mess up things in subtle ways.

**Comment by NP-compete** [comment]
Thanks

**Comment by dschaehi** [comment]
I also get the same error message on JupyterLab. Shouldn't this issue be reopened as the issue hasn't been solved yet?

**Comment by leej11** [comment]
I also get the same error message on JupyterLab unfortunately!

**Comment by GF-Huang** [comment]
So how to resolve it?

**Comment by reynoldyehezkiel** [comment]
This one works one me
https://github.com/ShopRunner/jupyter-notify/issues/33#issuecomment-488235980
