### ISSUE TITLE
Error whiler registering magic

### ISSUE THREAD

**Issue by zmjjmz** [ShopRunner/jupyter-notify#5]
Hey so I get this when I try and register the magic on Jupyter 5.0.0, Python 2.7.9, and IPython 5.4.1

```
import jupyternotify
a = get_ipython()
a.register_magics(jupyternotify.JupyterNotifyMagics)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-bd02226b31cf> in <module>()
      1 import jupyternotify
      2 a = get_ipython()
----> 3 a.register_magics(jupyternotify.JupyterNotifyMagics)

/home/u1/zach/proj/dataplayground2/local/lib/python2.7/site-packages/IPython/core/magic.pyc in register(self, *magic_objects)
    385             if isinstance(m, type):
    386                 # If we're given an uninstantiated class
--> 387                 m = m(shell=self.shell)
    388 
    389             # Now that we have an instance, we can register it and update the

/home/u1/zach/proj/dataplayground2/local/lib/python2.7/site-packages/jupyternotify/jupyternotify.pyc in __init__(self, shell)
     12 class JupyterNotifyMagics(Magics):
     13     def __init__(self, shell):
---> 14         super().__init__(shell)
     15         with open(resource_filename("jupyternotify", "js/init.js")) as jsFile:
     16             jsString = jsFile.read()

TypeError: super() takes at least 1 argument (0 given)
```

Let me know if you need anymore detail

**Comment by zmjjmz** [comment]
Actually: changing the offending line to

`super(JupyterNotifyMagics,self).__init__(shell)` seems to fix that part, I don't seem to be getting notifications at all.

**Comment by mdagost** [comment]
Yeah, sorry about that.  Just realized I was using python 3.  I just merged in a fix.  It's working for me in fresh virtualenv's for both 2 and 3.

**Comment by mdagost** [comment]
Actually, I'll leave this open until you confirm that it works...

**Comment by zmjjmz** [comment]
Yeah it doesn't seem to work unfortunately but I can't determine why -- no error message just getting no notifications -- probably ok to close and I'll make a new issue once/if I can dig a bit deeper and figure out what's wrong.

**Comment by mdagost** [comment]
What browser and version are you on? Can you pop open dev tools?

**Comment by zmjjmz** [comment]
Chromium Version 55.0.2883.87 (64-bit)


I do see an error about widgets not being available -- does this depend on that?

**Comment by zmjjmz** [comment]
Hey -- I actually do see it. Closing this.

**Comment by mdagost** [comment]
Oh good!
