### ISSUE TITLE
How to use remotely?

### ISSUE THREAD

**Issue by vg-pulsepoint** [ShopRunner/jupyter-notify#9]
How would I use this if the Jupyter session were running on a remote server? Could you please point me to some setup instructions.

**Comment by mdagost** [comment]
The same instructions on the README will work in a remote server.  Just pip install the package and do what's needed inside the notebook.

**Comment by binxuan** [comment]
Are you sure it is working properly on a remote server? I tried it on three servers as well as my local laptop. Only the local one works.

**Comment by mdagost** [comment]
@binxuan I just got it to work on a remote server.  Looks like you need to have the notebook running on https for it to work.  I'll add a note to the README.

**Comment by binxuan** [comment]
@mdagost Yes, you are right. Using https should fix this issue. Thanks.
